spring:
  application:
    name: service-registry
  cloud:
    config:
      profile: dev
  config:
    import: optional:configserver:http://localhost:8888



#spring:
#  application:
#    name: service-registry
#
#server:
#  port: 8761
#
#eureka:
#  client:
#    fetch-registry: false
#    register-with-eureka: false
#  service-url:
#    defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
#  instance:
#    hostname: service-registry



