spring:
  application:
    name: service-registry

server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  service-url:
    defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  instance:
    hostname: service-registry



