spring:
  application:
    name: payment-service
  cloud:
    config:
      profile: dev
  config:
    import: configserver:http://localhost:8888

#server:
#  port: 0
#spring:
#  application:
#    name: payment-service
#  datasource:
#    username: postgres
#    password: 12345
#    url: jdbc:postgresql://localhost:5432/payment
#  jpa:
#    show-sql: true
#    open-in-view: false
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: update
#
#  kafka:
#    producer:
#      bootstrap-servers: http://192.168.1.101:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#  cloud:
#    openfeign:
#      circuitbreaker:
#        enabled: true
#
#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    instance-id: ${spring.application.name}:${random.int}:${random.value}
#    prefer-ip-address: true


