spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        default-label: main
        git:
          uri: https://github.com/MedetHasanUgurlu/rent-a-car-microservice-confighub
          force-pull: true

server:
  port: 8888
